class layananhigo_page {

    layananhigo_menu="//label[@class='peer-checked:hidden']//div[@class='cursor-pointer grid grid-cols-l-fill items-center py-3']"
    wifiadvertising_sub_menu="//label[@class='peer-checked:hidden']//span[contains(text(),'WiFi Advertising')]"
    higospot_sub_menu="//label[@class='peer-checked:hidden']//span[contains(text(),'HIGOspot')]"
    agency_sub_menu="//label[@class='peer-checked:hidden']//span[contains(text(),'Integrated Digital Agency')]"

    image="//img[@alt='WiFi Advertising']"
    wording_title="//h1[normalize-space()='WiFi Advertising']"
    wording_desc="(//p[@class='z-10 text-sm text-white duration-700 animate-in fade-in slide-in-from-bottom-12 @2xl/page:text-lg'])[1]"

    wording_footprint="//h2[normalize-space()='Footprint HIGO']"
    wording_footprint_desc="(//p[@class='text-center text-sm @3xl/page:text-lg'])[1]"
    footprint_mrt="(//li)[13]"
    footprint_transjkt="(//li)[14]"
    footprint_asdp="(//li)[15]"
    footprint_airplane="(//li)[16]"
    footprint_foodbeverage="(//li)[17]"
    footprint_livingquarter="(//li)[18]"
    footprint_lrt="(//li)[19]"
    footprint_officelocation="(//li)[20]"
    footprint_shoppingdestination="(//li)[21]"

    wording_kenaliuser="//h2[contains(text(),'Kenali pengguna melalui 4 langkah pendekatan yang ')]"
    img_pembuatanprofil="//img[@alt='Pembuatan profil']"
    wording_pembuatanprofil="//h6[normalize-space()='Pembuatan profil']"
    wording_pembuatanprofil_desc="//span[contains(text(),'User mengisi informasi seperti nama, email, nomor ')]"
    img_penayangan="//img[@alt='Penayangan']"
    wording_penayangan="//h6[normalize-space()='Penayangan']"
    wording_penayangan_desc="//span[normalize-space()='Ads berupa gambar statis selama 3 detik.']"
    img_interaksi="//img[@alt='Interaksi']"
    wording_interaksi="//h6[normalize-space()='Interaksi']"
    wording_interaksi_desc="//span[contains(text(),'Menampilkan ads interaktif berupa game, video, ata')]"
    img_responlangsung="//img[@alt='Respons langsung']"
    wording_responlangsung="//h6[normalize-space()='Respons langsung']"
    wording_responlangsung_desc="//span[contains(text(),'Tahap di mana user dibawa keluar dari environment ')]"

    wording_campaign="//h2[normalize-space()='Maksimalkan campaign dengan CTR & completed view']"
    wording_campaign_desc="(//p[@class='text-sm @3xl/page:text-lg @3xl:max-w-120'])[1]"
    wording_estimatedclick="//h4[normalize-space()='Estimated click through rate']"
    wording_estimatedclick_desc="//p[contains(text(),'Optimalkan strategi marketing dan tingkatkan inter')]"
    wording_estimatedview="//h4[normalize-space()='Estimated completed view']"
    wording_estimatedview_desc="//p[contains(text(),'Tingkatkan strategi iklan dengan metrik akurat dar')]"

    wording_keuntungan="//h2[normalize-space()='Keuntungan menggunakan WiFi ads']"
    wording_keuntungan_desc="(//p[@class='text-center text-sm text-white @3xl/page:text-lg'])[1]"
    img_keuntungan1="//img[@alt='Menargetkan audiens secara terarah']"
    wording_keuntungan1="//h6[normalize-space()='Menargetkan audiens secara terarah']"
    wording_keuntungan1_desc="//p[contains(text(),'Targetkan audiens secara spesifik baik digital ata')]"
    img_keuntungan2="//img[@alt='Audiens berkualitas']"
    wording_keuntungan2="//h6[normalize-space()='Audiens berkualitas']"
    wording_keuntungan2_desc="//p[contains(text(),'Semua audiens yang terhubung melalui HIGO adalah n')]"
    img_keuntungan3="//img[@alt='Konten & tujuan terkustomisasi sepenuhnya']"
    wording_keuntungan3="//h6[normalize-space()='Konten & tujuan terkustomisasi sepenuhnya']"
    wording_keuntungan3_desc="//p[contains(text(),'Sesuaikan tujuan WiFi dengan fitur interaktif sepe')]"
    img_keuntungan4="//img[@alt='Insight audiens mendalam']"
    wording_keuntungan4="//h6[normalize-space()='Insight audiens mendalam']"
    wording_keuntungan4_desc="//p[contains(text(),'Dapatkan insight lebih dari sekadar perilaku digit')]"

    wording_mitrakami="//h2[normalize-space()='Mitra kami']"
    images_mitra="(//div[@class='grid grid-cols-3 gap-x-12 overflow-hidden *:mx-auto *:max-w-20 @xl/section:grid-cols-5 @4xl/section:grid-cols-7'])[1]"

    img_targetaudience="//img[@alt='Target Audience']"
    wording_targetaudience="//h6[contains(text(),'Capai hasil campaign lebih efektif dengan targeted')]"
    wording_btn="(//span[@class='font-sans font-medium text-sm text-blue-700 transition-colors duration-300 group-hover/button:text-white'])[1]"
    beriklansekarang_btn="(//a[@class='group/button z-10 grid w-fit grid-flow-col items-center gap-x-1 rounded-full bg-tint-0 px-3 py-2 transition-colors duration-300 hover:bg-tint-1 @xl/page:px-4 @xl/page:py-3'])[1]"
}
module.exports = new layananhigo_page()